INSERT INTO airline VALUES ("Jet Blue");
INSERT INTO airline VALUES ("Delta Air Line");
INSERT INTO airline VALUES ("Southwest");
INSERT INTO airline VALUES ("United");
INSERT INTO airline VALUES ("American Airlines");
INSERT INTO airline VALUES ("British Airways");
INSERT INTO airline VALUES ("Alaska Airlines");
INSERT INTO airline VALUES ("Air France");
INSERT INTO airline VALUES ("Air Canada");
INSERT INTO airline VALUES ("American Eagle Airlines");