insert into airport (code, name, city, country, airport_type) values ('DNG', 'Doongan Airport', 'Nanortalik', 'Greenland', 'international');
insert into airport (code, name, city, country, airport_type) values ('AIH', 'Aiambak Airport', 'Arrentela', 'Portugal', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('CIA', 'Ciampino–G. B. Pastine International Airport', 'Frydrychowice', 'Poland', 'both');
insert into airport (code, name, city, country, airport_type) values ('LEJ', 'Leipzig/Halle Airport', 'Paranaíba', 'Brazil', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('ZGU', 'Gaua Island Airport', 'Saga-shi', 'Japan', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('AKD', 'Akola Airport', 'Kaparéllion', 'Greece', 'international');
insert into airport (code, name, city, country, airport_type) values ('FLG', 'Flagstaff Pulliam Airport', 'Paragominas', 'Brazil', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('YBC', 'Baie Comeau Airport', 'Taizhou', 'China', 'both');
insert into airport (code, name, city, country, airport_type) values ('YPW', 'Powell River Airport', 'Orléans', 'France', 'international');
insert into airport (code, name, city, country, airport_type) values ('SUR', 'Summer Beaver Airport', 'Shangjiangxu', 'China', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('ALO', 'Waterloo Regional Airport', 'Meniko', 'Cyprus', 'both');
insert into airport (code, name, city, country, airport_type) values ('YUJ', 'Lady Franklin Point Airport', 'Jiaqu', 'China', 'both');
insert into airport (code, name, city, country, airport_type) values ('ILO', 'Iloilo International Airport', 'Haiyu', 'China', 'both');
insert into airport (code, name, city, country, airport_type) values ('XSP', 'Seletar Airport', 'Barão de São Miguel', 'Portugal', 'both');
insert into airport (code, name, city, country, airport_type) values ('DAC', 'Hazrat Shahjalal International Airport', 'Nice', 'France', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('KPO', 'Pohang Airport (G-815/K-3)', 'Yong’an', 'China', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('MKP', 'Makemo Airport', 'Boto', 'Indonesia', 'both');
insert into airport (code, name, city, country, airport_type) values ('MOQ', 'Morondava Airport', 'Prachatice', 'Czech Republic', 'both');
insert into airport (code, name, city, country, airport_type) values ('LDZ', 'Londolozi Airport', 'Longmen', 'China', 'international');
insert into airport (code, name, city, country, airport_type) values ('HYA', 'Barnstable Municipal Boardman Polando Field', 'Qijia', 'China', 'domestic');
insert into airport (code, name, city, country, airport_type) values ('PVG', 'Shanghai Pudong International Airport', 'Shanghai', 'China', 'both');
insert into airport (code, name, city, country, airport_type) values ('JFK', 'John F. Kennedy International Airport', 'New york', 'United States', 'both');
