insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 199, 'Realcube', '2021-10-24', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 77, 'Livefish', '2023-03-22', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 131, 'Skinix', '2021-06-15', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 57, 'Photofeed', '2023-03-27', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 101, 'Vitz', '2022-10-07', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 120, 'Rhybox', '2020-08-11', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 57, 'Riffpath', '2021-04-21', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 66, 'Vimbo', '2021-03-19', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 119, 'Brainbox', '2021-12-23', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 83, 'Katz', '2020-12-04', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 101, 'Quatz', '2022-05-14', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 102, 'Eamia', '2021-09-04', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 114, 'Muxo', '2022-11-24', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 158, 'Dabjam', '2021-10-15', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 86, 'Digitube', '2023-02-25', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 45, 'Jayo', '2022-11-12', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 198, 'Youtags', '2021-11-24', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 175, 'Teklist', '2020-10-28', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 154, 'Eamia', '2020-12-13', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 79, 'Kayveo', '2021-01-13', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 182, 'Skinix', '2020-04-08', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 114, 'Teklist', '2021-07-15', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 95, 'Topicshots', '2021-12-26', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 129, 'Zoomcast', '2021-03-09', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 84, 'Dynabox', '2022-05-23', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 197, 'Twitterworks', '2021-08-30', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 60, 'Lazz', '2022-01-10', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 134, 'Skinder', '2022-08-19', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 74, 'Thoughtblab', '2022-03-13', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 148, 'Quimm', '2023-03-25', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 142, 'Babbleset', '2021-07-16', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 177, 'Babbleblab', '2021-07-02', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 108, 'Meevee', '2020-04-19', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 136, 'Voonder', '2022-07-05', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 124, 'Gabcube', '2021-12-16', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 161, 'Browsedrive', '2022-01-26', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 123, 'Meetz', '2023-03-04', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 144, 'Vinder', '2022-08-04', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 106, 'Innotype', '2022-10-04', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 56, 'Roomm', '2021-05-09', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 33, 'Dabvine', '2022-09-07', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 171, 'Myworks', '2020-11-20', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 187, 'Jazzy', '2021-04-20', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 120, 'Roomm', '2020-05-09', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 100, 'Innojam', '2020-07-21', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 161, 'Gabvine', '2020-02-06', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 57, 'Cogibox', '2020-06-18', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 74, 'Flashdog', '2021-01-14', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 176, 'Skinder', '2022-04-15', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 140, 'Mydo', '2020-12-09', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 65, 'Meeveo', '2020-03-06', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 64, 'Eimbee', '2021-11-04', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 154, 'Innotype', '2020-04-30', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 95, 'Quimba', '2022-11-14', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 124, 'Midel', '2020-10-14', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 85, 'Yambee', '2020-07-19', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 161, 'Chatterpoint', '2021-01-24', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 103, 'Zazio', '2021-12-05', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 195, 'Oozz', '2022-06-27', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 180, 'Yombu', '2021-04-09', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 32, 'Oyoyo', '2021-10-22', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 171, 'Thoughtmix', '2022-11-17', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 188, 'Jaxbean', '2020-09-09', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 60, 'Aivee', '2020-09-28', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 60, 'Pixoboo', '2022-09-11', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 67, 'Quire', '2022-04-23', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 80, 'Divape', '2020-06-10', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 74, 'Jaloo', '2021-06-28', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 179, 'Eayo', '2022-02-07', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 111, 'Buzzshare', '2021-07-22', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 178, 'Flashpoint', '2021-07-10', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 189, 'Camido', '2021-12-29', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 78, 'Photofeed', '2021-10-17', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 125, 'Midel', '2021-11-06', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 49, 'Eidel', '2021-11-19', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 189, 'Voomm', '2023-02-07', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 193, 'Babblestorm', '2022-12-29', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 100, 'Kimia', '2022-09-07', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 58, 'Chatterpoint', '2022-08-29', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 73, 'Quinu', '2021-07-28', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 190, 'Browsebug', '2020-12-22', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 114, 'Livetube', '2022-04-02', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 50, 'Skaboo', '2020-09-22', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 109, 'Topicware', '2022-08-22', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Alaska Airlines', 199, 'Photobug', '2021-04-13', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 98, 'Divavu', '2022-05-17', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Airlines', 135, 'Quire', '2022-03-06', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Southwest', 115, 'Eire', '2022-08-05', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 51, 'Flipbug', '2022-01-19', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('United', 38, 'Kimia', '2021-08-14', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 43, 'Ozu', '2022-12-01', 2);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 57, 'Flipbug', '2020-05-04', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 125, 'Twinder', '2020-09-15', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Delta Air Line', 104, 'Twitterlist', '2022-07-10', 4);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('American Eagle Airlines', 180, 'Aibox', '2020-05-23', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air France', 53, 'Jetpulse', '2023-01-11', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('British Airways', 130, 'Kanoodle', '2022-11-16', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Air Canada', 114, 'DabZ', '2022-05-01', 1);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 172, 'Dynazzy', '2021-10-11', 3);
insert into airplane (airline_name, seat_number, manufacturing_company, manufacturing_date, age) values ('Jet Blue', 62, 'Devcast', '2021-10-29', 4);
